"""Shared enumerations and constant values used across the LFA application."""

SPOT_SELECTION_SUBSTRATE = "Substrate"
SPOT_SELECTION_ADSORBATE = "Adsorbate"
SPOT_SELECTION_SUPERSTRUCTURE = "Superstructure"

REFINEMENT_DIRECT_CLICK = "Direct Click"
REFINEMENT_MAX_PIXEL = "Max Pixel"
REFINEMENT_GAUSSIAN_FIT = "2D Gaussian Fit"
REFINEMENT_PARABOLA_3X3 = "Parabolic 3x3"
REFINEMENT_LOCAL_DFT = "Local DFT Upsample"

LATTICE_TYPE_HEXAGONAL = "hexagonal"
LATTICE_TYPE_SQUARE = "square"
LATTICE_TYPE_CUSTOM = "custom"

ADSORBATE_LATTICE_TYPE_UNKNOWN = "Unknown"
ADSORBATE_LATTICE_TYPE_HEXAGONAL = "Hexagonal"
ADSORBATE_LATTICE_TYPE_SQUARE = "Square"

PREDEFINED_SUBSTRATE_NONE = "None (Define a_surf below)"
PREDEFINED_SUBSTRATE_CUSTOM = "<Manual Definition...>"
PREDEFINED_SUBSTRATE_FROM_SELECTION = "<From Selection (Future)>"
