# lfa/gui/dialogs/real_space_reconstruction_dialog.py
import logging
from typing import Optional, Dict, Any, List, Tuple

import numpy as np
from PyQt6.QtCore import Qt, pyqtSlot
from PyQt6.QtWidgets import (
    QDialog, QVBoxLayout, QHBoxLayout,
    QLabel, QWidget, QGroupBox, QMessageBox, QSpinBox,
    QFormLayout, QRadioButton, QSplitter, QDialogButtonBox, QPushButton, QCheckBox, QComboBox
)

try:
    import pyqtgraph as pg
    from pyqtgraph import GraphicsLayoutWidget, ImageItem, ViewBox, RectROI, ScatterPlotItem
    PYQTGRAPH_AVAILABLE = True
except ImportError:
    pg = None
    GraphicsLayoutWidget = None
    ImageItem = None
    ViewBox = None
    RectROI = None
    ScatterPlotItem = None # Add missing import for clarity
    PYQTGRAPH_AVAILABLE = False
    logging.error("RealSpaceReconstructionDialog: PyQtGraph not found.")

# Import necessary backend functions and data structures
from ...core.history import HistoryNode
from ...analysis.fft_engine import calculate_fft
from ...analysis.peak_fitting import _gaussian_2d, fit_2d_gaussian_in_roi_with_all_data

logger = logging.getLogger(__name__)


class RealSpaceReconstructionDialog(QDialog):
    """
    A dialog for reconstructing real-space images from Fourier space data and
    for calculating autocorrelation maps (Patterson function).

    This dialog provides three main modes of operation:
    1.  **Autocorrelation**: Calculates the autocorrelation of the FFT power spectrum.
        This is useful for visualizing real-space periodicities directly from the FFT.
    2.  **Mask with ROIs**: Allows the user to draw rectangular regions of interest (ROIs)
        on the FFT. An inverse FFT is then performed on the masked data to reveal
        the real-space features corresponding to the selected frequencies.
    3.  **Mask with Spots**: Allows the user to select specific points (spots) on the FFT.
        A mask is generated by placing Gaussian profiles at these spots, followed by
        an inverse transform.
    """
    def __init__(self,
                 magnitude_fft_data: np.ndarray,
                 parent=None):
        """
        Initializes the Real Space Reconstruction dialog.

        Args:
            magnitude_fft_data (np.ndarray): The 2D numpy array containing the
                                             FFT magnitude or power spectrum data.
            parent (QWidget, optional): The parent widget. Defaults to None.
        """
        super().__init__(parent)
        self.setWindowTitle("Real Space Reconstruction from FFT")
        self.setMinimumSize(1200, 700)
        current_flags=self.windowFlags()
        self.setWindowFlags(current_flags | Qt.WindowType.WindowMinimizeButtonHint | Qt.WindowType.WindowMaximizeButtonHint)


        self.magnitude_fft_data = magnitude_fft_data
        
        # --- Internal State ---
        self.current_mode = "autocorrelation"
        self.mask_array: Optional[np.ndarray] = None
        self.roi_items: list[RectROI] = []
        self.selected_spots_px: List[Tuple[float, float]] = []
        self.spot_markers: Optional[ScatterPlotItem] = None

        # --- UI Initialization ---
        self._init_ui()
        self._connect_signals()
        
        # --- Initial State Setup ---
        self._on_mode_changed() # Set initial visibility of controls
        if self.original_fft_item:
            self.original_fft_item.setImage(self.magnitude_fft_data.T)

    def _init_ui(self):
        """Initializes all user interface elements and layouts for the dialog."""
        main_layout = QVBoxLayout(self)
        
        # --- Top Controls Section ---
        controls_group = QGroupBox("Reconstruction Controls")
        controls_layout = QHBoxLayout(controls_group)
        self._create_controls(controls_layout)
        main_layout.addWidget(controls_group)
        
        # --- Main Display Area with Splitter ---
        display_splitter = QSplitter(Qt.Orientation.Horizontal)
        
        # Left Panel: Original FFT and ROI selection
        fft_widget = GraphicsLayoutWidget()
        self.fft_plot = fft_widget.addPlot(title="Original FFT (Select regions here)")
        self.original_fft_item = ImageItem()
        self.fft_plot.addItem(self.original_fft_item)
        self.fft_plot.setAspectLocked(True)

        # Middle Panel: Mask Preview
        mask_widget = GraphicsLayoutWidget()
        self.mask_plot = mask_widget.addPlot(title="Mask Preview")
        self.mask_item = ImageItem()
        self.mask_plot.addItem(self.mask_item)
        self.mask_plot.setAspectLocked(True)

        # Right Panel: Reconstructed Image
        reco_widget = GraphicsLayoutWidget()
        self.reco_plot = reco_widget.addPlot(title="Reconstructed Real Space")
        self.reco_item = ImageItem()
        self.reco_plot.addItem(self.reco_item)
        self.reco_plot.setAspectLocked(True)
        
        # Refinement ROI for spot selection mode
        self.refinement_roi = RectROI(pos=(0, 0), size=(7, 7), pen=pg.mkPen('y', width=2), movable=True, resizable=False)
        self.fft_plot.addItem(self.refinement_roi)
        self.refinement_roi.setVisible(False)  # Hidden by default

        display_splitter.addWidget(fft_widget)
        display_splitter.addWidget(mask_widget)
        display_splitter.addWidget(reco_widget)
        main_layout.addWidget(display_splitter, 1)

        # --- Dialog Buttons ---
        self.button_box = QDialogButtonBox(QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel)
        main_layout.addWidget(self.button_box)

    def _create_controls(self, layout: QHBoxLayout):
        """Creates and lays out the control widgets for the dialog."""
        # --- Mode Selection Group ---
        mode_group = QGroupBox("Mode")
        mode_layout = QVBoxLayout(mode_group)
        self.rb_autocorrelation = QRadioButton("Calculate Autocorrelation")
        self.rb_autocorrelation.setChecked(True)
        self.rb_roi_mask = QRadioButton("Mask with ROIs")
        self.rb_spot_mask = QRadioButton("Mask with Spots")
        mode_layout.addWidget(self.rb_autocorrelation)
        mode_layout.addWidget(self.rb_roi_mask)
        mode_layout.addWidget(self.rb_spot_mask)
        mode_layout.addStretch()
        layout.addWidget(mode_group)

        # --- Autocorrelation Options Group ---
        autocorr_options_group = QGroupBox("Autocorrelation Options")
        autocorr_layout = QFormLayout(autocorr_options_group)
        self.remove_dc_checkbox = QCheckBox("Remove DC Component")
        self.remove_dc_checkbox.setChecked(True)
        self.remove_dc_checkbox.setToolTip("Removes the central (0,0) peak from FFT before calculating autocorrelation to avoid a bright, broad background.")
        self.scaling_combo = QComboBox()
        self.scaling_combo.addItems(["Log Power", "Power Spectrum", "Linear Magnitude", "Square Root"])
        self.scaling_combo.setToolTip("Selects the scaling for the autocorrelation display.\n'Log Power' is best for viewing weak spots.\n'Power Spectrum' represents physical intensity.")
        autocorr_layout.addRow(self.remove_dc_checkbox)
        autocorr_layout.addRow("Display Scale:", self.scaling_combo)
        layout.addWidget(autocorr_options_group)
        self.autocorr_options_group = autocorr_options_group # Store reference

        # --- Actions Group ---
        action_group = QGroupBox("Actions")
        action_layout = QVBoxLayout(action_group)
        self.add_roi_button = QPushButton("Add ROI")
        self.symmetric_roi_checkbox = QCheckBox("Add Symmetric ROI")
        self.add_spot_button = QPushButton("Select Spot")
        self.spot_mask_size_spinbox = QSpinBox()
        self.spot_mask_size_spinbox.setMinimum(1)
        self.spot_mask_size_spinbox.setMaximum(20)
        self.spot_mask_size_spinbox.setValue(2) # Corresponds to sigma = 0.2
        self.spot_mask_size_spinbox.setToolTip("Sets the size (sigma) of the Gaussian mask for each spot.")
        self.clear_mask_button = QPushButton("Clear Mask")
        self.reconstruct_button = QPushButton("Reconstruct / Calculate")
        action_layout.addWidget(self.add_roi_button)
        action_layout.addWidget(self.symmetric_roi_checkbox)
        action_layout.addWidget(self.add_spot_button)
        action_layout.addWidget(self.spot_mask_size_spinbox)
        action_layout.addWidget(self.clear_mask_button)
        action_layout.addWidget(self.reconstruct_button)
        action_layout.addStretch()
        layout.addWidget(action_group)
        layout.addStretch()

    def _connect_signals(self):
        """Connects widget signals to their corresponding slots."""
        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)

        if self.fft_plot and self.fft_plot.scene():
            self.fft_plot.scene().sigMouseClicked.connect(self._handle_fft_image_click)

        # Mode changes
        self.rb_autocorrelation.toggled.connect(self._on_mode_changed)
        self.rb_roi_mask.toggled.connect(self._on_mode_changed)
        self.rb_spot_mask.toggled.connect(self._on_mode_changed)

        # Button actions
        self.reconstruct_button.clicked.connect(self._on_reconstruct_clicked)
        self.add_roi_button.clicked.connect(self._on_add_roi_clicked)
        self.clear_mask_button.clicked.connect(self._on_clear_mask_clicked)
        self.add_spot_button.clicked.connect(self._on_add_spot_clicked)

        # Mask parameter changes
        self.symmetric_roi_checkbox.stateChanged.connect(self._update_mask_from_rois)
        self.spot_mask_size_spinbox.valueChanged.connect(self._update_mask_from_spots)

    @pyqtSlot(object)
    def _handle_fft_image_click(self, event):
        """
        Handles mouse clicks on the FFT image view.
        In 'spot_mask' mode, this places the refinement ROI for spot selection.
        """
        if event.button() != Qt.MouseButton.LeftButton:
            return

        if self.current_mode == 'spot_mask':
            pos_viewbox = self.fft_plot.vb.mapSceneToView(event.scenePos())
            if self.fft_plot.vb.sceneBoundingRect().contains(pos_viewbox):
                roi_size = self.refinement_roi.size()
                # Center the refinement ROI on the click position
                roi_pos = (pos_viewbox.x() - roi_size.x() / 2, pos_viewbox.y() - roi_size.y() / 2)
                self.refinement_roi.setPos(roi_pos)
                self.refinement_roi.setVisible(True)
                event.accept()
        else:
            event.ignore()  # Ignore clicks in other modes

    @pyqtSlot()
    def _on_mode_changed(self):
        """Slot activated when the user switches between reconstruction modes."""
        is_autocorr = self.rb_autocorrelation.isChecked()
        is_roi_mode = self.rb_roi_mask.isChecked()
        is_spot_mode = self.rb_spot_mask.isChecked()

        # Update visibility of controls based on the selected mode
        self.autocorr_options_group.setVisible(is_autocorr)
        self.add_roi_button.setEnabled(is_roi_mode)
        self.symmetric_roi_checkbox.setEnabled(is_roi_mode)
        self.add_spot_button.setEnabled(is_spot_mode)
        self.spot_mask_size_spinbox.setVisible(is_spot_mode)
        self.clear_mask_button.setEnabled(is_roi_mode or is_spot_mode)
        self.reconstruct_button.setText("Calculate Autocorrelation" if is_autocorr else "Reconstruct from Mask")
        
        self.current_mode = "autocorrelation" if is_autocorr else ("roi_mask" if is_roi_mode else "spot_mask")

        # Clear any existing masks or results when changing modes
        self._on_clear_mask_clicked()

    @pyqtSlot()
    def _on_reconstruct_clicked(self):
        """Slot for the main action button. Delegates to the correct method based on mode."""
        logger.info(f"'{self.reconstruct_button.text()}' button clicked.")
        if self.current_mode == "autocorrelation":
            self._perform_autocorrelation()
        elif self.current_mode in ["roi_mask", "spot_mask"]:
            self._perform_reconstruction_from_mask()
        else:
            QMessageBox.information(self, "Not Implemented", f"Mode '{self.current_mode}' is not yet implemented.")

    @pyqtSlot()
    def _on_add_roi_clicked(self):
        """Adds a new, interactive RectROI to the FFT plot for masking."""
        h, w = self.magnitude_fft_data.shape
        roi_size = (w // 8, h // 8)
        roi_pos = (w // 2 - roi_size[0] // 2, h // 2 - roi_size[1] // 2)
        
        new_roi = RectROI(pos=roi_pos, size=roi_size, pen=pg.mkPen('y', width=2), movable=True, resizable=True)
        self.roi_items.append(new_roi)
        self.fft_plot.addItem(new_roi)
        new_roi.sigRegionChanged.connect(self._update_mask_from_rois)
        self._update_mask_from_rois() # Update mask immediately

    @pyqtSlot()
    def _on_add_spot_clicked(self):
        """Refines and adds a new spot to the list based on the refinement ROI position."""
        if not self.refinement_roi.isVisible():
            QMessageBox.warning(self, "No ROI", "Please click on the FFT image to place a refinement ROI first.")
            return

        roi_state = self.refinement_roi.getState()
        x0r, y0r = round(roi_state['pos'].x()), round(roi_state['pos'].y())
        w, h = round(roi_state['size'].x()), round(roi_state['size'].y())
        center_yx = (y0r + h // 2, x0r + w // 2)
        
        if fit_2d_gaussian_in_roi_with_all_data:
            # Attempt to refine the position using a 2D Gaussian fit
            fit_res = fit_2d_gaussian_in_roi_with_all_data(self.magnitude_fft_data, center_yx, w // 2)
            if fit_res:
                _, (refined_ky, refined_kx), _ = fit_res
                refined_pos = (float(refined_kx), float(refined_ky))
                self.selected_spots_px.append(refined_pos)
                logger.info(f"Added refined spot at: {refined_pos}")
                self._update_mask_from_spots()
                self._redraw_spot_markers()
            else:
                QMessageBox.warning(self, "Fit Failed", "Could not refine spot position with Gaussian fit. Using ROI center.")
                # Fallback to ROI center if fit fails
                self.selected_spots_px.append((float(center_yx[1]), float(center_yx[0])))
                self._update_mask_from_spots()
                self._redraw_spot_markers()
        else:
            # Fallback if fitting function is not available
            self.selected_spots_px.append((float(center_yx[1]), float(center_yx[0])))
            self._update_mask_from_spots()
            self._redraw_spot_markers()

    def _redraw_spot_markers(self):
        """Draws markers for the selected spots on the FFT plot."""
        if self.spot_markers:
            self.fft_plot.removeItem(self.spot_markers)
            self.spot_markers = None
            
        if self.selected_spots_px:
            self.spot_markers = pg.ScatterPlotItem(
                pos=np.array(self.selected_spots_px), symbol='+', size=15,
                pen=pg.mkPen('r', width=2)
            )
            self.fft_plot.addItem(self.spot_markers)

    def _update_mask_from_spots(self):
        """Creates and displays a mask by placing Gaussian profiles at selected spot locations."""
        if self.magnitude_fft_data is None:
            return
        h, w = self.magnitude_fft_data.shape
        mask = np.zeros((h, w), dtype=np.float32)
        
        # Prepare coordinate grid once
        Y, X = np.mgrid[0:h, 0:w]
        xy_tuple = (Y.flatten(), X.flatten())
        
        # Get sigma from the UI control, converting from int to float
        sigma = float(self.spot_mask_size_spinbox.value()) / 10.0

        for (kx, ky) in self.selected_spots_px:
            # Create a normalized Gaussian at each spot location
            amplitude = 1.0
            popt = [amplitude, ky, kx, sigma, sigma, 0, 0] # Assume symmetric Gaussian (sigma_x=sigma_y, theta=0)
            gauss_flat = _gaussian_2d(xy_tuple, *popt)
            mask += gauss_flat.reshape(h, w)
            
        if mask.max() > 0:
            mask /= mask.max()  # Normalize mask to range [0, 1]
            
        self.mask_array = mask
        self.mask_item.setImage(self.mask_array.T, autoLevels=True)
        self.mask_plot.autoRange()

    @pyqtSlot()
    def _on_clear_mask_clicked(self):
        """Removes all ROIs and spots, and clears the mask and reconstruction views."""
        # Remove ROI items from plot
        for roi in self.roi_items:
            self.fft_plot.removeItem(roi)
        self.roi_items.clear()
        
        # Clear spot data
        self.selected_spots_px.clear()
        self._redraw_spot_markers()
        self.refinement_roi.setVisible(False)
        
        # Clear display items
        self.mask_item.clear()
        self.reco_item.clear()
        self.mask_array = None
        
        logger.debug("Cleared all ROIs, spots, and masks.")

    def _perform_autocorrelation(self):
        """Calculates and displays the autocorrelation of the FFT power spectrum."""
        if self.magnitude_fft_data is None:
            return

        try:
            power_spectrum = self.magnitude_fft_data.copy()
            
            # Optionally remove the DC component to avoid a bright artifact in the center
            if self.remove_dc_checkbox.isChecked():
                rows, cols = power_spectrum.shape
                center_y, center_x = rows // 2, cols // 2
                power_spectrum[center_y, center_x] = 0

            logger.debug("Calculating FFT of power spectrum for autocorrelation...")
            autocorr_complex = np.fft.fft2(power_spectrum)
            autocorr_shifted = np.fft.fftshift(autocorr_complex)
            autocorr_map = np.abs(autocorr_shifted)
            
            # Apply display scaling for better visualization
            scaling_mode = self.scaling_combo.currentText()
            if scaling_mode == "Log Power":
                display_data = np.log1p(autocorr_map**2)
            elif "Power Spectrum" in scaling_mode:
                display_data = autocorr_map**2
            elif "Square Root" in scaling_mode:
                display_data = np.sqrt(autocorr_map)
            else:  # Linear Magnitude
                display_data = autocorr_map

            self.reco_item.setImage(display_data.T, autoLevels=True)
            self.reco_plot.setTitle("Autocorrelation (Patterson Map)")
            self.reco_plot.autoRange()
            
            logger.info("Autocorrelation calculated and displayed successfully.")
            
        except Exception as e:
            logger.exception(f"Error during autocorrelation calculation: {e}")
            QMessageBox.critical(self, "Calculation Error", f"Could not calculate autocorrelation: {e}")

    @pyqtSlot()
    def _update_mask_from_rois(self):
        """Generates and displays a mask by copying data from within the user-drawn ROIs."""
        if self.magnitude_fft_data is None:
            return
        h, w = self.magnitude_fft_data.shape
        mask = np.zeros((h, w), dtype=np.float32)
        center_x, center_y = w / 2, h / 2

        for roi in self.roi_items:
            pos = roi.pos()
            size = roi.size()
            x0, y0 = int(round(pos.x())), int(round(pos.y()))
            x1, y1 = x0 + int(round(size.x())), y0 + int(round(size.y()))
            
            # Clamp coordinates to be within the image bounds
            x0, x1 = np.clip([x0, x1], 0, w)
            y0, y1 = np.clip([y0, y1], 0, h)
            
            if x1 > x0 and y1 > y0:
                # Copy the magnitude data from the selected region into the mask
                mask[y0:y1, x0:x1] = self.magnitude_fft_data[y0:y1, x0:x1]

            # If symmetric mode is on, create a centrosymmetric copy of the ROI
            if self.symmetric_roi_checkbox.isChecked():
                # Calculate position of the symmetric ROI
                sym_x = 2 * center_x - (pos.x() + size.x())
                sym_y = 2 * center_y - (pos.y() + size.y())
                
                x0_s, y0_s = int(round(sym_x)), int(round(sym_y))
                x1_s, y1_s = x0_s + int(round(size.x())), y0_s + int(round(size.y()))

                # Clamp symmetric coordinates
                x0_s, x1_s = np.clip([x0_s, x1_s], 0, w)
                y0_s, y1_s = np.clip([y0_s, y1_s], 0, h)

                if x1_s > x0_s and y1_s > y0_s:
                    # Copy data from the symmetric region
                    mask[y0_s:y1_s, x0_s:x1_s] = self.magnitude_fft_data[y0_s:y1_s, x0_s:x1_s]
                
        self.mask_array = mask
        self.mask_item.setImage(self.mask_array.T, autoLevels=True)
        self.mask_plot.autoRange()

    def _perform_reconstruction_from_mask(self):
        """
        Performs a real-space reconstruction.
        
        Note: This is a simplified reconstruction. A true reconstruction would require
        the complex FFT data (magnitude and phase). This implementation applies a
        forward FFT to the masked *magnitude* data, which results in the
        autocorrelation of the features selected by the mask, not a direct
        image reconstruction.
        """
        if self.mask_array is None:
            QMessageBox.warning(self, "No Mask", "Please create a mask using ROIs or spots before reconstructing.")
            return

        try:
            logger.debug("Performing reconstruction from mask.")
            
            # Apply the mask to the original FFT magnitude data
            masked_fft_shifted = self.magnitude_fft_data * self.mask_array

            # Perform a forward FFT on the masked data.
            # This is equivalent to convolving the real-space representation of the
            # original image with the real-space representation of the mask.
            reconstructed_complex = np.fft.fft2(masked_fft_shifted)
            reconstructed_complex = np.fft.fftshift(reconstructed_complex)

            # Display the absolute magnitude of the result
            reconstructed_image = np.abs(reconstructed_complex)
            
            self.reco_item.setImage(reconstructed_image.T, autoLevels=True)
            self.reco_plot.setTitle("Reconstructed from Mask")
            self.reco_plot.autoRange()
            
            logger.info("Reconstruction from mask successful.")

        except Exception as e:
            logger.exception(f"Error during reconstruction from mask: {e}")
            QMessageBox.critical(self, "Reconstruction Error", f"Could not reconstruct image: {e}")